name: Deploy page
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build document
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ruby:2.7.8-slim-buster

    steps:
      # Add the building of the CV here as well
      - uses: actions/checkout@v2
      - name: Deploy document
        run: |
          
          git config --global user.email "xppcoder@gmail.com"
          git config --global user.name "jacarte"
          git config --global credential.helper cache
          git config --global --add safe.directory /__w/jacarte.github.io/jacarte.github.io
          
          #echo "en_US UTF-8" > /etc/locale.gen
          #locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US:en
          export LC_ALL=en_US.UTF-8

          bash ./bin/deploy_auto 
        env:
          REPO_KEY: '${{ secrets.REPO_KEY2 }}'
